# Classification based Collaborative Filtering Systems
## Logistic Regression Classifier
![](Chapter-2.png)

In [1]:
#importing libraries
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
from sklearn.linear_model import LogisticRegression

In [2]:
#importing bank data
bank_full = pd.read_csv('bank_full_w_dummy_vars.csv')
bank_full.head(10)

age           job   marital  education default  balance housing loan  \
0   58    management   married   tertiary      no     2143     yes   no   
1   44    technician    single  secondary      no       29     yes   no   
2   33  entrepreneur   married  secondary      no        2     yes  yes   
3   47   blue-collar   married    unknown      no     1506     yes   no   
4   33       unknown    single    unknown      no        1      no   no   
5   35    management   married   tertiary      no      231     yes   no   
6   28    management    single   tertiary      no      447     yes  yes   
7   42  entrepreneur  divorced   tertiary     yes        2     yes   no   
8   58       retired   married    primary      no      121     yes   no   
9   43    technician    single  secondary      no      593     yes   no   

   contact  day  ... job_unknown                   \
0  unknown    5  ...                            0   
1  unknown    5  ...                            0   
2  unknown    5  ...                            0   
3  unknown    5  ...                            0   
4  unknown    5  ...                            1   
5  unknown    5  ...                            0   
6  unknown    5  ...                            0   
7  unknown    5  ...                            0   
8  unknown    5  ...                            0   
9  unknown    5  ...                            0   

   job_retired                   job_services                  \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             0                             0   
4                             0                             0   
5                             0                             0   
6                             0                             0   
7                             0                             0   
8                             1                             0   
9                             0                             0   

   job_self_employed             job_unemployed                \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             0                             0   
4                             0                             0   
5                             0                             0   
6                             0                             0   
7                             0                             0   
8                             0                             0   
9                             0                             0   

  job_maid                     job_student                   \
0                            0                            0   
1                            0                            0   
2                            0                            0   
3                            0                            0   
4                            0                            0   
5                            0                            0   
6                            0                            0   
7                            0                            0   
8                            0                            0   
9                            0                            0   

   married                       single                        \
0                             1                             0   
1                             0                             1   
2                             1                             0   
3                             1                             0   
4                             0                             1   
5                             1                             0   
6           

In [3]:
bank_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 37 columns):
 #   Column                        Non-Null Count  Dtype 
---  ------                        --------------  ----- 
 0   age                           45211 non-null  int64 
 1   job                           45211 non-null  object
 2   marital                       45211 non-null  object
 3   education                     45211 non-null  object
 4   default                       45211 non-null  object
 5   balance                       45211 non-null  int64 
 6   housing                       45211 non-null  object
 7   loan                          45211 non-null  object
 8   contact                       45211 non-null  object
 9   day                           45211 non-null  int64 
 10  month                         45211 non-null  object
 11  duration                      45211 non-null  int64 
 12  campaign                      45211 non-null  int64 
 13  pdays           

In [48]:
#splitting our data 
#training data
x = bank_full.iloc[:, 18:37].values
#testing data or trget
y = bank_full.iloc[:, 17].values

In [49]:
print(y)

[0 0 0 ... 1 0 0]


In [50]:
#defining model (logisitc regression), instantiate
logreg = LogisticRegression()
#fitting
logreg.fit(x, y)

LogisticRegression()

In [51]:
#a user who works at management and is divorceed and single
#checkingi if this user is likely to buy the sales putvh
new_user = np.array([0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1])

In [54]:
new_user

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [55]:
np.reshape(new_user, (1, -1))

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]])

In [56]:
y

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [59]:
#reshaping the input
new_user = np.reshape(new_user, (1, -1))

In [62]:
#predicting if the user buys the pitch or not 
y_pred = logreg.predict(new_user)

In [63]:
y_pred

array([0], dtype=int64)

In [64]:
#thus sam will not accept the pitch from the bank according to our model